# Generated by Django 5.2.2 on 2025-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDoacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('cestas_basicas', models.PositiveIntegerField(default=0, verbose_name='Cestas Básicas')),
                ('roupas', models.PositiveIntegerField(default=0, verbose_name='Roupas')),
                ('agua_mineral', models.PositiveIntegerField(default=0, verbose_name='Água Mineral')),
                ('familias_impactadas', models.PositiveIntegerField(default=0, verbose_name='Famílias Impactadas')),
            ],
            options={
                'verbose_name': 'Registro de Doações',
                'verbose_name_plural': 'Registros de Doações',
            },
        ),
    ]
