# Generated by Django 5.2.2 on 2025-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodoacoes',
            name='agua_mineral',
        ),
        migrations.AddField(
            model_name='registrodoacoes',
            name='alimentos_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alimentos (kg)'),
        ),
        migrations.AddField(
            model_name='registrodoacoes',
            name='alimentos_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alimentos (toneladas)'),
        ),
        migrations.AddField(
            model_name='registrodoacoes',
            name='liquidos_litros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Líquidos (litros)'),
        ),
    ]
